theme: minima
title: Michael Loyselles GitBlog
author: Michael Loyselle
email: m.loyselle@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This first blog site, for Michael Loyselle. Here you will find information pertaining to programming and Michael's journey to become a proper programmer.

# social links
github_username: Leozas

show_excerpts: true # set to false to remove excerpts on the homepage
